When an important event (for example a fight between two groups) is witnessed, a brief, yet detailed, narrative description of the event should be included in the report. As you prepare each section, you will have to relate your narrative part to the quantitative part. The function of the narrative part is also to summarize what you did that month.


3- A logistics section, which should be used for reporting on equipment issues, computer issues, permits, assistants, etc.

The field/lab work section should includes information which is only related to work in the forest, lab work done associated with processing samples, other campañas done on that month.  One can think of the “Field/Lab Work” section as the data collection aspect of the research.

Data Management will include information limited to data entry, work related with the Palms and other obligations that may come up related to the project. You can think of it as data cleaning, processing and organization. 

The Logistics section 

Each section may have a narrative part and a quantitative part in order to develop a sound report that will describe your overall work of that month so that the directors and managers can schedule the work for the upcoming month.

The quantitative part is crucial because it is the one that will tell us that all the data have been entered, cleaned and organized.

Quantitative Section

The quantitative section will have in numbers a description of the work you did this month -- # of avistajes per group (or solitary), # of focals per individual, and # and type of biological samples collected, etc.

Some sections such as Demography will most likely not include a quantitative section. In these cases the narrative part is VERY important. There will be a Word document which will include all of the tables under the Overview bullet and tentative format needed for the report and the person preparing the report should fill each section of the tables to complete each part. Since the development of the report will be an ongoing process, tables can be added and modified to improve the format but should be standardized. By editing the tables and format and the standardizing them we will ensure every member of the project will submit the same format. It will save time for the preparer and the directors revising them.

IMPORTANT: Information for this quantitative section HAS to come from the database!!! Print out a query or another document that will facilitate this process but ALWAYS refer to the database. This will ensure that the numbers are right and that they are interpreted correctly by the directors.

Avistajes

Include a table summarizing avistajes done per observer per group and a few comments if considered necessary.

Example:

"AV08140 - Sept 12th while doing routine demography work I picked up a dead signal on the P300 collar (Faster beep rhythm). Found Anibal’s collar (orange/gray/orange, channel 26) on the ground with the ball chain broken at the base of the unit."

Total # Avistajes

Group Avistajes

Solitary Avistajes

Not Found



Demography


Focals

Include a table summarizing the number of focals done per observer per group per individual.  Some comments may be included if considered necessary or a reference to an attached Word document describing particular events in detail.

Example:

Group

AM

 


Age/Sex Class Totals


Special Projects

For example, a field trip for the National Geographic Owl Distribution/Demography Project (Sept 1st – Sept 5th).  Traveled to Pilcomayo National Park with Marcelo, Cecilia and Victor to search for owl monkey groups to take demography information on. 


DATA MANAGEMENT


Narrative

You may need to describe some particular situation regarding data, Palms not functioning (further detail on this topic should appear in the LOGISTICS section), somebody losing data, etc.


Quantitative

In this section we need to see ADDITIONAL evidence that the data have been entered, organized and cleaned.  Some of that evidence comes from the tables reporting avistajes, samples, etc., but it is also necessary to summarize some of the data here.

For example, if it is the birth season and you have been doing focals on the infant, a query to get some of those data ready would be useful.  Or a query obtaining the average group size for the month.   Or it may be that someone is working on an abstract or a manuscript and they can query the data to show that the data are there.  I.e., it should be something that forces you to work on the data that have been entered.
```


## LOGISTICS

This final section should include any requests for supplies and DETAIL any problems with equipment. Be sure to send us requests for supplies with ENOUGH LEAD TIME for us to get them and send them with the next folks coming to the field. Far too frequently, we are asked to buy supplies when there are no supplies left already!


d <- d[with(d, order(Date,`Time Enc`)), ]


NOTES ON JOINS

Currently dplyr supports four join types:

inner_join()
return all rows from x where there are matching values in y, and all columns from x and y. If there are multiple matches between x and y, all combination of the matches are returned.

left_join()
return all rows from x, and all columns from x and y. Rows in x with no match in y will have NA values in the new columns. If there are multiple matches between x and y, all combinations of the matches are returned.

right_join()
return all rows from y, and all columns from x and y. Rows in y with no match in x will have NA values in the new columns. If there are multiple matches between x and y, all combinations of the matches are returned.

semi_join()
return all rows from x where there are matching values in y, keeping just columns from x.

A semi join differs from an inner join because an inner join will return one row of x for each matching row of y, where a semi join will never duplicate rows of x.

anti_join()
return all rows from x where there are not matching values in y, keeping just columns from x.

full_join()
return all rows and all columns from both x and y. Where there are not matching values, returns NA for the one missing.


library(rvest)
feed_items <- read_xml("http://twiv.microbeworld.libsynpro.com/twiv") %>%
  xml_nodes("item")
Podcast date is stored in pubDate and duration in itunes:duration, so we can extract the text between those tags:

feed_items %>% 
  xml_nodes("pubDate") %>% 
  xml_text()

feed_items %>% 
  xml_nodes("itunes\\:duration") %>% 
  xml_text()
